name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --no-configuration-cache

      - name: Test Report
        if: (success() || failure())
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: build/test-results/**/*.xml
          reporter: java-junit
